# Generated by Django 4.1.1 on 2022-11-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_card", "0011_book_description"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksincart",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product_card.book",
                verbose_name="Book",
            ),
        ),
    ]
