# Generated by Django 4.1.1 on 2022-11-21 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product_card", "0011_book_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carts", "0007_alter_booksincart_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="good",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="good",
                to="product_card.book",
                verbose_name="good",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="quantity"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="customer",
            ),
        ),
    ]
