# Generated by Django 4.1.1 on 2022-11-21 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carts", "0008_cart_good_cart_quantity_alter_cart_customer"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="good",),
        migrations.RemoveField(model_name="cart", name="quantity",),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cart",
            ),
        ),
    ]
