# Generated by Django 4.1.1 on 2022-11-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0012_cart_quantity"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="good",),
        migrations.RemoveField(model_name="cart", name="quantity",),
    ]
