# Generated by Django 4.1.1 on 2022-11-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0015_alter_booksincart_cart_alter_cart_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booksincart",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="carts.cart",
                verbose_name="Cart",
            ),
        ),
    ]
