# Generated by Django 4.1.1 on 2022-11-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="additional_info",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="address",
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="city",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="country",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="index",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="phone",
            field=models.IntegerField(
                default=1, help_text="Enter the number in international format."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="reserve_address",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="surname",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appuser",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
