# Generated by Django 4.1.1 on 2022-12-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_appuser_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="address",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="city",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="country",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="appuser", name="index", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="phone",
            field=models.IntegerField(
                help_text="Enter the number in international format.", null=True
            ),
        ),
    ]
