# Generated by Django 4.1.1 on 2022-10-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookauthor",
            name="name",
            field=models.CharField(max_length=30, verbose_name="Author's name"),
        ),
        migrations.AlterField(
            model_name="bookauthor",
            name="surname",
            field=models.CharField(max_length=30, verbose_name="Author's surname"),
        ),
    ]
