# Generated by Django 4.1.1 on 2022-10-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0003_rename_name_bookauthor_name1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookauthor",
            name="surname2",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Author's surname"
            ),
        ),
    ]
