# Generated by Django 4.1.1 on 2022-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0004_alter_bookauthor_surname2"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookauthor",
            name="name3",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Author's name"
            ),
        ),
        migrations.AddField(
            model_name="bookauthor",
            name="surname3",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Author's name"
            ),
        ),
    ]
