# Generated by Django 4.1.1 on 2022-10-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0006_rename_name1_bookauthor_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="")),
                ("author", models.ManyToManyField(to="references.bookauthor")),
            ],
        ),
    ]
