# Generated by Django 4.1.1 on 2022-10-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0008_bookseries_delete_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_name", models.TextField(max_length=30, verbose_name="Genre")),
                (
                    "book_name",
                    models.CharField(max_length=30, verbose_name="Book name"),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookPublishingHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_name",
                    models.TextField(max_length=30, verbose_name="Publishing house"),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="bookauthor",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookseries",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
