# Generated by Django 4.1.1 on 2022-10-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "references",
            "0009_bookgenre_bookpublishinghouse_bookauthor_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="bookgenre", name="book_name",),
    ]
