# Generated by Django 4.1.1 on 2022-10-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0010_remove_bookgenre_book_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookseries", name="book_name",),
    ]
