# Generated by Django 4.1.1 on 2022-11-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Test",),
    ]
