# Generated by Django 4.1.1 on 2022-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_delete_test"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="contact_info",),
        migrations.AddField(
            model_name="order",
            name="additional_info",
            field=models.TextField(
                default=1,
                help_text="Please insert your delivery address and phone number if it's different from your account's data.",
                verbose_name="Additional info",
            ),
            preserve_default=False,
        ),
    ]
