# Generated by Django 4.1.1 on 2022-11-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_order_contact_info_order_additional_info"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="additional_info",),
        migrations.AddField(
            model_name="order",
            name="contact_info",
            field=models.TextField(
                default=1,
                help_text="Please insert your delivery address and phone number if it's different from you account's data.",
                verbose_name="Contact info",
            ),
            preserve_default=False,
        ),
    ]
