# Generated by Django 4.1.1 on 2022-11-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_additional_info_order_contact_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact_info",
            field=models.TextField(verbose_name="Contact info"),
        ),
    ]
