# Generated by Django 4.1.1 on 2022-11-30 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0016_alter_booksincart_cart"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0006_alter_order_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="carts.cart",
                verbose_name="Cart",
            ),
        ),
    ]
