# Generated by Django 4.1.1 on 2022-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_order_user_alter_order_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
