# Generated by Django 4.1.1 on 2022-10-09 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "references",
            "0009_bookgenre_bookpublishinghouse_bookauthor_description_and_more",
        ),
        ("product_card", "0002_book_binding_book_genre_book_pages_book_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="activity",
            field=models.CharField(
                default="Yes", max_length=3, verbose_name="Avaliability"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="age_restriction",
            field=models.IntegerField(default="16", verbose_name="Age restriction"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="available_books",
            field=models.IntegerField(default="15", verbose_name="Available books"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="date_of_addition",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date of addition"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="format",
            field=models.CharField(
                default="75 x 15", max_length=7, verbose_name="Format"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(default="12", max_length=30, verbose_name="ISBN"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="modification_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Modification date"),
        ),
        migrations.AddField(
            model_name="book",
            name="publishing_house",
            field=models.ManyToManyField(
                to="references.bookpublishinghouse",
                verbose_name="Publishing house/Publishing houses",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default="9", max_digits=2, verbose_name="Rating"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="weight",
            field=models.IntegerField(default="155", verbose_name="Weight"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Price"
            ),
        ),
    ]
