# Generated by Django 4.1.1 on 2022-10-09 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0011_remove_bookseries_book_name"),
        ("product_card", "0003_book_activity_book_age_restriction_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="author",),
        migrations.RemoveField(model_name="book", name="genre",),
        migrations.RemoveField(model_name="book", name="publishing_house",),
        migrations.RemoveField(model_name="book", name="series",),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="references.bookauthor",
                verbose_name="Author/Authors",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="references.bookgenre",
                verbose_name="Genre",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="publishing_house",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="references.bookpublishinghouse",
                verbose_name="Publishing house/Publishing houses",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="references.bookseries",
                verbose_name="Series",
            ),
            preserve_default=False,
        ),
    ]
