# Generated by Django 4.1.1 on 2022-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0011_remove_bookseries_book_name"),
        ("product_card", "0004_remove_book_author_remove_book_genre_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="author",),
        migrations.RemoveField(model_name="book", name="genre",),
        migrations.RemoveField(model_name="book", name="publishing_house",),
        migrations.RemoveField(model_name="book", name="series",),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(
                to="references.bookauthor", verbose_name="Author/Authors"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(
                to="references.bookgenre", verbose_name="Genre"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publishing_house",
            field=models.ManyToManyField(
                to="references.bookpublishinghouse",
                verbose_name="Publishing house/Publishing houses",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="series",
            field=models.ManyToManyField(
                to="references.bookseries", verbose_name="Series"
            ),
        ),
    ]
