# Generated by Django 4.1.1 on 2022-10-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0011_remove_bookseries_book_name"),
        ("product_card", "0005_remove_book_author_remove_book_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(to="references.bookauthor"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(to="references.bookgenre"),
        ),
        migrations.RemoveField(model_name="book", name="publishing_house",),
        migrations.RemoveField(model_name="book", name="series",),
        migrations.AddField(
            model_name="book",
            name="publishing_house",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="references.bookpublishinghouse",
                verbose_name="Publishing house/Publishing houses",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="references.bookseries",
                verbose_name="Series",
            ),
            preserve_default=False,
        ),
    ]
