# Generated by Django 4.1.1 on 2022-10-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_card", "0007_alter_book_price_alter_book_publishing_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=70, verbose_name="Book name"),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Currency in BYN",
                max_digits=5,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="weight",
            field=models.IntegerField(
                help_text="Weight in grams", verbose_name="Weight"
            ),
        ),
    ]
