# Generated by Django 4.1.1 on 2022-10-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_card", "0008_alter_book_name_alter_book_price_alter_book_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
